-- Insert sample training programs (only if tables are empty)
INSERT INTO public.training_programs (
  title, description, training_type, disaster_types, status,
  start_date, end_date, location_name, latitude, longitude,
  state, district, organizing_body, target_participants, actual_participants, budget
) VALUES
  (
    'Earthquake Preparedness Workshop',
    'Comprehensive training on earthquake response and safety protocols',
    'workshop',
    ARRAY['earthquake']::disaster_type[],
    'ongoing',
    NOW() - INTERVAL '2 days',
    NOW() + INTERVAL '3 days',
    'Delhi Administrative Training Institute',
    28.6139,
    77.2090,
    'Delhi',
    'New Delhi',
    'NDMA',
    150,
    120,
    500000.00
  ),
  (
    'Flood Response Drill',
    'Practical field exercise for flood disaster management',
    'drill',
    ARRAY['flood']::disaster_type[],
    'planned',
    NOW() + INTERVAL '7 days',
    NOW() + INTERVAL '9 days',
    'Patna Training Center',
    25.5941,
    85.1376,
    'Bihar',
    'Patna',
    'Bihar SDMA',
    200,
    0,
    750000.00
  ),
  (
    'Cyclone Awareness Campaign',
    'Public awareness program on cyclone preparedness',
    'awareness_campaign',
    ARRAY['cyclone']::disaster_type[],
    'completed',
    NOW() - INTERVAL '15 days',
    NOW() - INTERVAL '13 days',
    'Visakhapatnam Community Center',
    17.6868,
    83.2185,
    'Andhra Pradesh',
    'Visakhapatnam',
    'Coastal NGO Network',
    500,
    480,
    300000.00
  ),
  (
    'Fire Safety Simulation',
    'Advanced fire safety and evacuation simulation training',
    'simulation',
    ARRAY['fire']::disaster_type[],
    'ongoing',
    NOW() - INTERVAL '1 day',
    NOW() + INTERVAL '2 days',
    'Mumbai Fire Training Academy',
    19.0760,
    72.8777,
    'Maharashtra',
    'Mumbai',
    'Maharashtra Fire Services',
    100,
    85,
    450000.00
  ),
  (
    'Multi-Hazard Response Training',
    'Integrated training covering multiple disaster scenarios',
    'field_exercise',
    ARRAY['earthquake', 'flood', 'landslide']::disaster_type[],
    'planned',
    NOW() + INTERVAL '14 days',
    NOW() + INTERVAL '17 days',
    'Dehradun Training Ground',
    30.3165,
    78.0322,
    'Uttarakhand',
    'Dehradun',
    'NDMA',
    250,
    0,
    1000000.00
  )
ON CONFLICT DO NOTHING;
